### ISSUE TITLE
I believe my computer deleted the host.bak file and it wont work now but it worked the first few times after my testing it

### ISSUE THREAD

**Issue by Moonked** [kaczorws/xboxappmod#10]
![Screenshot 2020-11-29 204511](https://user-images.githubusercontent.com/75230323/100560441-cc064680-3283-11eb-8aae-8ae28de315fb.png)
It keeps giving me this error and I don't understand what to do because I completed the prerequisites and it still gives me this. I uninstalled the mod and the companion app multiple times and it won't work. It would be much obliged if you can help me.

**Comment by kaczorws** [comment]
This is strange as the script does not remove the original hosts file, it only updates it. Have you checked if the hosts.bak file is in the script directory by any chance? Also, have you manually checked C:\WINDOWS\System32\Drivers\etc\hosts location if any version of hosts is in there?

**Comment by Moonked** [comment]
I checked it and it wasn't there

**Comment by kaczorws** [comment]
If hosts file is not there and you have not changed it before in any way then you can manually recreate it. Go to `C:\WINDOWS\System32\Drivers\etc\` and create a text file called `hosts` (without any extensions). Default hosts file content is this:

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
```
You will need admin rights to create this file there.

After that you can try running the script again.

**Comment by Moonked** [comment]
Thank you so much it worked, I wanted my games to look good on here and now they do. Thank you
