### ISSUE TITLE
Xbox Series X?

### ISSUE THREAD

**Issue by ShocWave** [kaczorws/xboxappmod#12]
This isn't an issue, but the Xbox Series S|X uses a new app for remote streaming.
Will you be updating the script to support it?

https://www.microsoft.com/en-ca/p/xbox-game-streaming-test-app/9nzbpvpnldgm?activetab=pivot:overviewtab
The package can be downloaded and slideloaded here: https://store.rg-adguard.net/

**Comment by kaczorws** [comment]
Unfortunately I do not own new Xbox Series S|X and without it I won't be able to update the script (although in this case it seems a completely new script for another app would be required).

**Comment by ShocWave** [comment]
What if I allow you to connect to my Xbox remotely?
I'm not sure if there is any script at all. Since I could not find any files in json format in the application folder.
________________________________

**Comment by kaczorws** [comment]
Unfortunately I don't think it would work remotely as local connection is required to test quality difference properly. If I ever purchase Series X I would try to update the script.
