### ISSUE TITLE
A new app Xbox game streaming (Test app)

### ISSUE THREAD

**Issue by RenanBan** [kaczorws/xboxappmod#13]
I got a Series S, and this app is the only one that works right now to stream xbox to pc, but it only streams in 720p, there is a way to look at that and probably make a config to run it at a better quality?

**Comment by kaczorws** [comment]
Unfortunately I do not own Series S (or X) so I am unable to test the connection with this new app. If I purchase any of the new consoles I will definitely try to update the script.
