### ISSUE TITLE
"Xbox App settings file corrupted or Microsoft modified the structure. Please check for new version of the script."

### ISSUE THREAD

**Issue by Zo0m1** [kaczorws/xboxappmod#16]
I haven't done anything since the last time I used this, I reinstalled it and everything, but I keep getting this error and I can't find any new version. I saw another resolved issue like this but I didn't understand what the OP did to fix it. I don't think this is an issue on my end because someone else has had it recently? I last used this thing like a month ago if that helps. Maybe it's just a coincidence, but I wanna fix it no matter what.

**Comment by kaczorws** [comment]
It is currently not working for me either. Microsoft must have changed something either in the config file or the app itself. I'm working on a fix but not sure when it will be available.

**Comment by Zo0m1** [comment]
okay ty, also my resolution randomly changes after I run it and it gives me this error and my amd radeon software gets messed up and I have to reinstall my graphics drivers, Idk if this is a coincidence or related just very weird  and I wanted to point it out because if it is related its really annoying :(

**Comment by iamtheezac** [comment]
waiting on that fix, hope you figure out! I love this script :)

**Comment by DoNotArgueToxicGames** [comment]
As for the file not found. For the time being (as none of the switches worked for me at the moment)
the directory can be found at C:\Users\**YourUserName**\AppData\Local\Packages\Microsoft.XboxApp_(randomletters and numbers)\LocalState (mine was _\AppData\Local\Packages\Microsoft.XboxApp_8wekyb3d8bbwe\LocalState_ )

just hardcode the settings.json around line 40
**_$XboxConfigPath = $env:LOCALAPPDATA + "\Packages\Microsoft.XboxApp_8wekyb3d8bbwe\LocalState\settings.json"_**

The next issue is the if statement around line 60
_If (($XboxConfigFileCorrupted -contains $true)) { }_
if you change it to
_**If (-not $XboxConfigFileCorrupted) {} it works fine**_

**Comment by kaczorws** [comment]
OK, I finally managed to find some time to take a look at this. 
As @DoNotArgueToxicGames already pointed out, $XboxConfigFileCorrupted required some modifications as Microsoft changed the structure of the Settings.json file and the -match simply did not work (they added single space and broke my regex because hey why not).

I uploaded 1.0.1 pre-release which manages to open the script and the Xbox App BUT (this is the sad part) it seems they changed the domain from which settings are taken from so when the Xbox App opens, the settings are reverted instantly to original bad quality.

By looking through https://docs.microsoft.com/en-us/windows/privacy/manage-windows-20h2-endpoints I tried using other domains pointed there like:

127.0.0.1  settings-win.data.microsoft.com
127.0.0.1  dlassets-ssl.xboxlive.com
127.0.0.1  cy2.settings.data.microsoft.com.akadns.net

but it seems none of these works. Also I tried using WireShark but it looks like Xbox App is connecting to Azure Cloud services using different IP everytime but I wasn't able to trace any of these to any domain (tried nslookup).

If anyone could find the right domain I would be very grateful as I do not have time currently to look into this more in near future.

**Comment by DoNotArgueToxicGames** [comment]
The other problem is that you're still trying to connect to the old streaming app for the Xbox One X.

Xbox  Series S and X don't use Microsoft.XboxApp they use Microsoft.GamingApp and the XboxPcApp.exe executable.

From the networking monitoring I have done the only domain(s) I could see of interest is(are) indeed.
dlassets-ssl.xboxlive.com
dlassets-ssl.xboxlive.com.edgekey.net

- Udp: SrcPort = DNS(53), DstPort = 62275, Length = 192
    SrcPort: DNS(53)
    DstPort: 62275
    TotalLength: 192 (0xC0)
    Checksum: 40956 (0x9FFC)
    UDPPayload: SourcePort = 53, DestinationPort = 62275
- Dns: QueryId = 0x4446, QUERY (Standard query), Response - Success, 2A02:26F0:5D00:397:0:0:0:57, 2A02:26F0:5D00:383:0:0:0:57 ... 
    QueryIdentifier: 17478 (0x4446)
  + Flags:  Response, Opcode - QUERY (Standard query), RD, RA, Rcode - Success
    QuestionCount: 1 (0x1)
    AnswerCount: 4 (0x4)
    NameServerCount: 0 (0x0)
    AdditionalCount: 0 (0x0)
  - QRecord: dlassets-ssl.xboxlive.com of type AAAA on class Internet
     QuestionName: dlassets-ssl.xboxlive.com
     QuestionType: AAAA, IPv6 Address, 28(0x1c)
     QuestionClass: Internet, 1(0x1)
  - ARecord: dlassets-ssl.xboxlive.com of type CNAME on class Internet: dlassets-ssl.xboxlive.com.edgekey.net
     ResourceName: dlassets-ssl.xboxlive.com
     ResourceType: CNAME, Canonical name for an alias, 5(0x5)
     ResourceClass: Internet, 1(0x1)
     TimeToLive: 3232 (0xCA0)
     ResourceDataLength: 39 (0x27)
     CName: dlassets-ssl.xboxlive.com.edgekey.net
  - ARecord: dlassets-ssl.xboxlive.com.edgekey.net of type CNAME on class Internet: e87.dspg.akamaiedge.net
     ResourceName: dlassets-ssl.xboxlive.com.edgekey.net
     ResourceType: CNAME, Canonical name for an alias, 5(0x5)
     ResourceClass: Internet, 1(0x1)
     TimeToLive: 81 (0x51)
     ResourceDataLength: 22 (0x16)
     CName: e87.dspg.akamaiedge.net
  - ARecord: e87.dspg.akamaiedge.net of type AAAA on class Internet: 2A02:26F0:5D00:397:0:0:0:57
     ResourceName: e87.dspg.akamaiedge.net
     ResourceType: AAAA, IPv6 Address, 28(0x1c)
     ResourceClass: Internet, 1(0x1)
     TimeToLive: 17 (0x11)
     ResourceDataLength: 16 (0x10)
     IPv6Address: 2A02:26F0:5D00:397:0:0:0:57
  - ARecord: e87.dspg.akamaiedge.net of type AAAA on class Internet: 2A02:26F0:5D00:383:0:0:0:57
     ResourceName: e87.dspg.akamaiedge.net
     ResourceType: AAAA, IPv6 Address, 28(0x1c)
     ResourceClass: Internet, 1(0x1)
     TimeToLive: 17 (0x11)
     ResourceDataLength: 16 (0x10)
     IPv6Address: 2A02:26F0:5D00:383:0:0:0:57

I will see what I can find.

**Comment by DoNotArgueToxicGames** [comment]
Extra info:
after a lot of testing and trial and error It seems The SeriesX and SeriesS still need the Xbox Companion App installed

**Comment by DoNotArgueToxicGames** [comment]
More info and debugging:
Although it seems the companion app is still needed (but the series X doesn't or can't even use it) it seems the whole settings.json isn't used by the SeriesS and SeriesX

Below is a small log from files being accessed, modified, removed (I have hidden my windows name) this is opening the Xbox app and using the new streaming functionality for the SeriesX from within the Xbox app (not the console companion)

this is monitoring the following folders:
C:\Users\\*USER NAME*\AppData\Local\Packages 
and
C:\Program Files\WindowsApps

```
New (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt.~tmp
Modified (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices
New (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt~RF21e8b857.TMP
New (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db-journal
Deleted (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt~RF21e8b857.TMP
Renamed (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt.~tmp -> c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt
Renamed (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt -> c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt~RF21e8b857.TMP
Modified (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\DiagOutputDir\XboxAppServices\ftc_log.txt
Modified (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState
Modified (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db
Deleted (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db-journal
Modified (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\Microsoft\CryptnetUrlCache\MetaData\77EC63BDA74BD0D0E0426DC8F8008506
New (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kglDL.bin
Modified (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache
Deleted (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kglDL.bin
New (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kgl.bin
Deleted (24-11-2021 17:02:12): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kgl.bin
New (24-11-2021 17:02:13): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\4L1ZUDYP\links[1].json
Modified (24-11-2021 17:02:13): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\4L1ZUDYP\links[1].json
Deleted (24-11-2021 17:02:13): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\links[2].json
Modified (24-11-2021 17:02:13): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db
Modified (24-11-2021 17:02:14): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T
Modified (24-11-2021 17:02:14): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db
Modified (24-11-2021 17:02:16): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db
New (24-11-2021 17:02:17): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\Temp\mat-debug-18640.log
Modified (24-11-2021 17:02:17): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\TempState\d0e0bd479af0445eb368d83796596621.db.ses
Modified (24-11-2021 17:02:17): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\TempState\d0e0bd479af0445eb368d83796596621.db-shm
Modified (24-11-2021 17:02:17): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\TempState\d0e0bd479af0445eb368d83796596621.db-wal
Modified (24-11-2021 17:02:17): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\gamestreaming_log_0.txt
Modified (24-11-2021 17:02:17): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db
New (24-11-2021 17:02:19): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\storehome[2].json
Modified (24-11-2021 17:02:19): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\storehome[2].json
Deleted (24-11-2021 17:02:19): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\storehome[1].json
Modified (24-11-2021 17:02:19): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T
Modified (24-11-2021 17:02:20): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db
Deleted (24-11-2021 17:02:20): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db-journal
New (24-11-2021 17:02:21): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\subscriptions[2].json
Modified (24-11-2021 17:02:21): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\subscriptions[2].json
Deleted (24-11-2021 17:02:21): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\subscriptions[1].json
New (24-11-2021 17:02:21): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\RWPy9C[1].jpg
Modified (24-11-2021 17:02:21): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\INetCache\FGOBLP6T\RWPy9C[1].jpg
New (24-11-2021 17:02:41): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kglDL.bin
Modified (24-11-2021 17:02:41): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache
Deleted (24-11-2021 17:02:41): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kglDL.bin
New (24-11-2021 17:02:41): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kgl.bin
Deleted (24-11-2021 17:02:41): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalCache\kgl.bin
New (24-11-2021 17:02:47): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db-journal
Modified (24-11-2021 17:02:47): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db
Modified (24-11-2021 17:02:47): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState
Deleted (24-11-2021 17:02:47): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\AsyncStorage.db-journal
Modified (24-11-2021 17:02:47): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\logs.zip
Modified (24-11-2021 17:02:47): c:\Users\**USER NAME**\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\gamestreaming_log_0.txt
```

I don't think the old settings.json method will work for SeriesS or SeriesX

**Comment by kaczorws** [comment]
This script is no longer maintained - worked only on old pre-2021 Xbox App (which supported only Xbox One/One S/One X).
