### ISSUE TITLE
Accidentally closed script manually

### ISSUE THREAD

**Issue by tvkym** [kaczorws/xboxappmod#2]
'Very High' setting no longer comes up normally, And 'start.bat' keeps saying that I need to run Xbox streaming once, even though I have.

**Comment by kaczorws** [comment]
You probably closed the script when it was restoring settings.json file (file with quality settings which xbox app uses). First of all, go to script directory and locate hosts.bak and settings.json.bak files. Make copy of them someplace safe (They could come handy if the solution below won't work).

Then try running the xbox app normally (NOT using the script, normally from the start menu). The app should automatically download the correct file. 

After that you should normally be able to run the script.

Let me know if this helps.
