### ISSUE TITLE
Feature request: "To manually end script..."

### ISSUE THREAD

**Issue by daetanbhuck** [kaczorws/xboxappmod#4]
Hiya kaczorws,

Thanks so much for your fine, open-source work.

Could your script please include an option to manually end? That is, after "waiting for XboxApp process to end..." Like, "[A] to auto-end XboxApp and script:"

I ran into a problem yesterday when I quit XboxApp (and couldn't find it in the Task Manager), but the script didn't conclude. Thankfully, when I shut my computer down (whoops) the script finished.

PS Do you have suggested setting for Battlefield 5? The default settings push just past 35mbps, causing artifacts.

**Comment by daetanbhuck** [comment]
Nevermind! It looks like "Esc" does a check on if the XboxApp is closed. (I don't know PS so maybe?)

PS 50 720 30 :( I got 70 1080 60 working with QoS, but there's a lag every 3-4 seconds that's playable, generally, but not on high-speed multiplayer BF5. Open to suggestions :)

**Comment by kaczorws** [comment]
Hello,

The name of the process is XboxApp.exe and it is in most occasions a child process of svchost.exe. It is not always visible in normal Task Manager but you can always see it in tools like Process Explorer.

I think that you must have somehow paused the script and that is why it didn't notice the missing XboxApp process. Pressing "Esc" unpaused it and then it ended normally.

As for the recommended settings, unfortunately I do not own Battlefield V so can't suggest anything. The most bitrate is taken by frames per second setting, so if you can live with 30fps, you can stay at this setting and then experiment with higher resolution and quality.

Hope this helps :)
