### ISSUE TITLE
Doesn't appear to affect stream quality

### ISSUE THREAD

**Issue by binarymelon** [kaczorws/xboxappmod#5]
The script runs for me and appears to modify the settings file, but I'm not seeing any effect on the stream bitrate/quality.  I also noticed I had additional properties (GAME_STREAMING_VERY_HIGH_QUALITY_SETTINGS_INTERNAL and GAME_STREAMING_VERY_HIGH_QUALITY_SETTINGS_PUBLIC_PREVIEW), but even after updating the script to also update those properties I'm not seeing any difference.  I'm only getting about 2-4 Mbit average bitrate.  I've tested this while wired (gigabit) and wireless (haven't tested local, but gets 300Mbits+ down on speed tests).  Xbox is wired and network tests show it's able to get over 500Mbits down.

**Comment by kaczorws** [comment]
Hello, sorry for late reply. Could you check if the Settings.json file is still updated after you run the script and while the Xbox App is still running (before you close it)? Also, it seems that settings with INTERNAL and PUBLIC_PREVIEW suffix are not used, only GAME_STREAMING_HIGH_QUALITY_SETTINGS, so only this one should be updated. Also, please check which version of Xbox App are you using - I just tested on 44.44.7002.00000 (latest) and seems to be working fine, reached peak bitrate of 56mbps.

**Comment by binarymelon** [comment]
I just tested on the same version and I see don't see any difference.  I verified that the Settings.json was updated. Below is the value while the app is running.

```"GAME_STREAMING_VERY_HIGH_QUALITY_SETTINGS": "70000000,1080,30,59,0,10,40,170",```
