### ISSUE TITLE
Not working after windows update

### ISSUE THREAD

**Issue by miikearthur** [kaczorws/xboxappmod#6]
I think the last windows update broke the script. The official xbox app is not called xbox anymore, maybe it's because of that. Is it possible to fix it? This script has made my remote playing experience so much better since forever.

Great work, and thank you in advance!

**Comment by kaczorws** [comment]
Hi, I just updated Windows to the latest version (I'm on build 1903) as well as the Xbox App (version 48.55.30001.00000) and everything seems to be working fine. Although in the latest Windows build the app has been renamed to Xbox Console Companion, it is still executed through the same command (start xbox:) and streaming using it is working for me without any issues.

Could you tell me what exactly is not working for you?
