### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sasorrii** [kaczorws/xboxappmod#8]
Hi i know long time has passed and i dont know it this script still working i have error lite this:
![script](https://user-images.githubusercontent.com/68013046/86918485-15b09200-c127-11ea-97aa-b6b747a2bbcc.jpg)

**Comment by kaczorws** [comment]
Hello,
Looks like you did not change the execution policy on your system. Take a look at https://github.com/kaczorws/xboxappmod in "Prerequisites" section. You need to change Execution Policy to Unrestricted in order to run the script.
