### ISSUE TITLE
Set-ExecutionPolicy Unrestricted error

### ISSUE THREAD

**Issue by Senpai2000** [kaczorws/xboxappmod#9]
![image](https://user-images.githubusercontent.com/58580295/95678125-d7fe5200-0bca-11eb-8590-8374d97c4619.png)

**Comment by Senpai2000** [comment]
![IMG_20201011_141904.jpg](https://user-images.githubusercontent.com/58580295/95678406-bc944680-0bcc-11eb-9a63-3f20fd443701.jpg)

**Comment by kaczorws** [comment]
Sorry for late reply, it seems that you have no authority to change the powershell execution policy on your machine. It such case there is not much you can do unless you contact the administrator of that machine.
